pipeline {
    agent any

    tools {
        // Optionnel si tu veux forcer un JDK installé dans Jenkins
        // nom du JDK configuré dans Manage Jenkins > Global Tool Configuration
        jdk 'jdk-17'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/mohamedgader/MadrassaCloud_BE.git'
            }
        }

        stage('Build') {
            steps {
                bat 'mvnw.cmd clean package -DskipTests'
            }
        }

        stage('Test') {
            steps {
                bat 'mvnw.cmd test'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Déploiement... (à compléter selon ton besoin)'
            }
        }
    }
}
