pipeline {
    agent any

    tools {
        jdk 'jdk-17'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/mohamedgader/MadrassaCloud_BE.git'
            }
        }

        stage('Check Java') {
            steps {
                bat 'java -version'
            }
        }

        stage('Build') {
            steps {
                dir('ITTrack_BE/ITTrack_BE') {   // 🔥 aller dans le bon dossier
                    bat 'mvnw.cmd clean package -DskipTests'
                }
            }
        }

        stage('Test') {
            steps {
                dir('ITTrack_BE/ITTrack_BE') {
                    bat 'mvnw.cmd test'
                }
            }
        }
    }
}
